name: POC Environment Approval

on:
  workflow_dispatch:

jobs:
  wait-for-approval:
    runs-on: ubuntu-latest

    environment:
      name: poc-approval

    steps:
      - name: Deployment approved
        run: |
          echo "Approval received."
          echo "This is just a proof of concept."
